name: packages
description: Resolves a package name to its path on your HD
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/Mike Mitterer/dart-packages

version: 0.4.1

environment:
  sdk: '>=1.8.0 <2.0.0'

# Add the bin/packages.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  packages:

dependencies:
  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'

  args: ^1.0.0

  path: ^1.3.0

  optional: ^2.0.0
    # path: /Volumes/Daten/DevLocal/DevDart/optional.dart

dev_dependencies:
  # There is a reference to Grind in tests - so don't remove it!
  # Activate grinder globally with: pub global activate grinder
  grinder: any
  test: any

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0