name: packages
description: Resolves a package name to its path on your HD
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/Mike Mitterer/dart-packages

version: 0.1.7

environment:
  sdk: '>=1.8.0 <2.0.0'

# Add the bin/packages.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  packages:

dependencies:
  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0

  args: ^0.13.0

  path: ^1.3.0

dev_dependencies:
  test: any
  grinder: any